# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad2cfc817fd0257bf262e7a15656c92c7e4408d3dd38da5c2279176dc01dbd7f468498988839e7bd909d56233082f94b5b0efd50a59a3d91e787156029cd44f1

test:
  secret_key_base: 543d51e80b6cfac36e3c15f80c8f2066cb4220fb47ae471f84036907cd9d1f303f00cce94ae05e268d4d5f2a4528de71ad3db5db3725de10d70a1c63e9c9c594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
