# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5015f1252b31e1072ce840a06ce4b98775c2054fbda4e2cbd394b8ce0d2164aba0994e1bd5f88d04955c6ae549cf6f9d7eb0dc0cce3eff1e2fb965e8cbdd602

test:
  secret_key_base: 6d1cac07eeda3b4b06ac6aa1f0e652114a054ac122896813cd2618c164145773b6fde606dd6b89ffcee49dbff3a91777f92007472870b8245465a6afbb254ecb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
